apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-deployment-gke-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-deployment-gke
        image: gcr.io/gcp-devops-390912/gcpdevops-dev:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
---
apiVersion: "v1"
kind: Service
metadata:
  name: "gcp-devops-gke-service-dev"
  namespace: "gcp-devops-dev"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "gcp"
  type: "LoadBalancer"
